# Generated by Django 6.0.5 on 2026-05-07 16:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='actual_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='expected_completion',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.client')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity_fulfilled', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated to Production'), ('PARTIAL', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(limit_choices_to={'category': 'FIN'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.clientorder')),
            ],
            options={
                'unique_together': {('order', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Filled in on completion', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('material', models.ForeignKey(help_text='The finished product being manufactured', limit_choices_to={'category': 'FIN'}, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('product_batch', models.OneToOneField(blank=True, help_text='Set when the run is completed and a product batch is recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_run', to='inventory.productbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity_available', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — not yet ordered'), ('ORDERED', 'Ordered from supplier'), ('IN_TRANSIT', 'In Transit'), ('IN_WAREHOUSE', 'In Warehouse'), ('RESERVED', 'Reserved for this run'), ('CONSUMED', 'Consumed / used in production'), ('SHORT', 'Shortage — insufficient quantity')], default='PENDING', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(limit_choices_to={'category__in': ['RAW', 'PKG']}, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('raw_material_batch', models.ForeignKey(blank=True, help_text='Set when a specific batch is assigned to this component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterialbatch')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.productionrun')),
            ],
            options={
                'ordering': ['production_run', 'material__name'],
                'unique_together': {('production_run', 'material')},
            },
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productionrun'),
        ),
        migrations.CreateModel(
            name='ProductionRunAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.clientorderline')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.productionrun')),
            ],
            options={
                'unique_together': {('production_run', 'order_line')},
            },
        ),
        migrations.DeleteModel(
            name='ManufacturingOrder',
        ),
    ]
