# Generated by Django 6.0.5 on 2026-05-09 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_alter_workflowtask_actual_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Optional reference e.g. ORDER-42', max_length=100),
        ),
        migrations.AlterField(
            model_name='productioncomponent',
            name='raw_material_batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch assigned to this component', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterialbatch'),
        ),
        migrations.AlterField(
            model_name='productioncomponent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending — not yet ordered'), ('ORDERED', 'Ordered from supplier'), ('IN_WAREHOUSE_RAW', 'In Warehouse as raw material'), ('IN_PROCESS', 'Processed for production'), ('FINAL_PRODUCT', 'Stored as Final Product')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='product_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_run', to='inventory.productbatch'),
        ),
        migrations.CreateModel(
            name='ProductionRunShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.DecimalField(decimal_places=3, max_digits=15)),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('order_line', models.ForeignKey(blank=True, help_text='The order line this shipment fulfils (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.clientorderline')),
                ('production_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='inventory.productionrun')),
            ],
            options={
                'ordering': ['-shipped_at'],
            },
        ),
        migrations.DeleteModel(
            name='WorkflowTask',
        ),
    ]
