# Generated by Django 6.0.5 on 2026-05-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_materialtransaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='raw_material_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.rawmaterialbatch'),
        ),
    ]
