# Generated by Django 6.0.5 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_materialtransaction_raw_material_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PKG', 'Packaging'), ('FIN', 'Finished Product'), ('CON', 'Consumables'), ('FXC', 'Fixed Costs')], max_length=3),
        ),
    ]
