# Generated by Django 6.0.5 on 2026-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN'),
        ),
    ]
