# Generated by Django 6.0.5 on 2026-05-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_client_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialbatch',
            unique_together={('material', 'lot_number')},
        ),
    ]
