# Generated by Django 6.0.5 on 2026-05-20 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_rawmaterialbatch_lot_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_reservations', to='inventory.clientorderline')),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.productbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
