# Generated by Django 6.0.5 on 2026-06-05 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productbatchreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncomponent',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='productioncomponent',
            name='raw_material_batch',
        ),
        migrations.RemoveField(
            model_name='productioncomponent',
            name='status',
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending — not yet ordered'), ('ORDERED', 'Ordered from supplier'), ('IN_WAREHOUSE_RAW', 'In Warehouse as Raw Material')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('PURCHASE_ORDER', 'Purchase Order'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PURCHASE_ORDER', max_length=25),
        ),
        migrations.CreateModel(
            name='RawBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_allocations', to='inventory.productionrun')),
                ('raw_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.rawmaterialbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
