# Generated by Django 6.0.5 on 2026-06-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_productioncomponent_actual_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(limit_choices_to={'category': 'FIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='production_template', to='inventory.material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=15)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.productiontemplate')),
            ],
            options={
                'ordering': ['material__name'],
            },
        ),
    ]
