# Generated by Django 6.0.5 on 2026-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productiontemplate_productiontemplatecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawbatchallocation',
            name='date_shipped',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawbatchallocation',
            name='transporter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
