# Generated by Django 6.0.5 on 2026-07-01 04:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_rawbatchallocation_date_shipped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRunReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_reservations', to='inventory.clientorderline')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reservations', to='inventory.productionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
