# Generated by Django 6.0.5 on 2026-07-02 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_productionrunreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncomponent',
            name='material',
            field=models.ForeignKey(limit_choices_to={'category__in': ['RAW', 'PKG', 'FIN']}, on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
    ]
