# Generated by Django 6.0.5 on 2026-07-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_productioncomponent_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatchreservation',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_component_reservations', to='inventory.productionrun'),
        ),
        migrations.AlterField(
            model_name='productbatchreservation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_reservations', to='inventory.clientorderline'),
        ),
    ]
