# Generated by Django 6.0.5 on 2026-07-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productbatchreservation_production_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncomponent',
            name='material',
            field=models.ForeignKey(limit_choices_to={'category__in': ['RAW', 'PKG', 'FIN', 'CON']}, on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
    ]
