# Generated by Django 6.0.5 on 2026-07-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_carrier_supplier_clientorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact3_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact3_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact3_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
