# Generated by Django 6.0.5 on 2026-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_client_contact1_email_client_contact1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text='ERP supplier code e.g. ΠΡΟΜ-00000281', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tin',
            field=models.CharField(blank=True, max_length=50, verbose_name='TIN/ΑΦΜ'),
        ),
    ]
