# Generated by Django 6.0.5 on 2026-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_salesorder_salesorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
