# Generated by Django 6.0.5 on 2026-08-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_salesorder_date_delivered_supplyorder_date_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_prefix', models.CharField(choices=[('02', '02 — Olive oil products'), ('03', '03 — Bakery / rusks'), ('04', '04 — Vinegars'), ('05', '05 — Lifestyle / gifts'), ('06', '06 — Food products'), ('08', '08 — Tea'), ('10', '10 — Marmalade'), ('11', '11 — Tea cans')], max_length=2, unique=True)),
                ('lead_time_months', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Lead Time Config',
                'ordering': ['sku_prefix'],
            },
        ),
        migrations.CreateModel(
            name='ReorderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.DecimalField(decimal_places=4, default='0.9500', help_text='Target service level, e.g. 0.95 for 95%', max_digits=5)),
                ('z_score', models.DecimalField(decimal_places=6, default='1.644854', help_text='Z-score corresponding to service level (auto-hint: 0.95→1.645, 0.99→2.326)', max_digits=8)),
                ('months_window', models.PositiveIntegerField(default=6, help_text='Number of monthly sales files to use for calculations')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reorder Settings',
            },
        ),
    ]
