# Generated by Django 6.0.5 on 2026-08-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_leadtimeconfig_reordersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reordersettings',
            name='service_level',
            field=models.DecimalField(decimal_places=4, default='0.9500', help_text='Target service level, e.g. 0.95 for 95%', max_digits=6),
        ),
    ]
