# Generated by Django 6.0.5 on 2026-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_reordersettings_service_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pack',
            field=models.PositiveIntegerField(blank=True, help_text='Units per carton box', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pallet_high',
            field=models.PositiveIntegerField(blank=True, help_text='Layers per pallet', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pallet_tie',
            field=models.PositiveIntegerField(blank=True, help_text='Boxes per pallet layer', null=True),
        ),
    ]
