# Generated by Django 6.0.5 on 2026-08-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_material_pack_material_pallet_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialbatch',
            name='status',
        ),
    ]
