# Generated by Django 6.0.5 on 2026-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_rawmaterialbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='carton_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Carton height in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gross weight per unit in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net weight per unit in kg', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='pallet_tie',
            field=models.PositiveIntegerField(blank=True, help_text='Boxes per pallet layer (120x80cm)', null=True),
        ),
    ]
