# Generated by Django 6.0.5 on 2026-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_material_carton_height_material_gross_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Gross weight per unit in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Net weight per unit in kg', max_digits=10, null=True),
        ),
    ]
