# Generated by Django 6.0.5 on 2026-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_material_gross_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reordersettings',
            name='selected_months',
            field=models.JSONField(blank=True, default=list, help_text='List of YYYY-MM strings to include in ROP calculation'),
        ),
    ]
