# Generated by Django 6.0.5 on 2026-08-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_reordersettings_selected_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reordersettings',
            name='months_window',
        ),
    ]
